import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "ALL GPT",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>
                    {/* sidebar */}

                    <div className="bg-[#343541] flex-1"> {children}</div>
                </div>
            </body>
        </html>
    );
}
